### ISSUE TITLE
Usage instructions / supported features

### ISSUE THREAD

**Issue by tmbo** [sebastianmika/pyduckling#1]
We'd love to use the project for our conversational AI framework https://github.com/rasaHQ/rasa_nlu, but at the moment there 
- are no usage instructions
- is no documentation about the supported features.
- isn't any information about supported platforms (windows, osx, linux?)

Thanks for the work you've put into the wrapper :+1:

**Comment by sebastianmika** [comment]
Thanks for your interest. I am afraid, but I will not be able to add a lot to this stub in the next time - at least I cannot promise. Quickly addressing your points:

* I added an example how to use (within docker)
* Supported features are very limited. Language should all work by passing "EN", "DE", "FR", and alike to `parse_time`; parsing other dimensions than just time requires to adjust the code in `DucklingFFI.hs` (you can look at the `Duckling.Debug.parse` function as a guideline) and the upstream definitions: 
    * swig spec in `pyduckling.i` to add a new parameter to the `parse` function (the dimension you are asking for)
    * same in `DucklingFFI_stub.h` and `pyduckling_stub.h` header files
* Supported platforms: I only use this within docker. I wouldn't know for Windows, but I doubt that there would be issues using it in any *nix style system.
