### ISSUE TITLE
TypeError: parse_time() takes from 1 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by jackieju** [sebastianmika/pyduckling#2]
Hi,

When I try the example code, it throw exception:
TypeError: parse_time() takes from 1 to 3 positional arguments but 4 were given
I check the __init__.py code, the mothod declare it has 3 parameters. But the sample 
parse_time('nächsten Montag', 'week', 'DE', now)
passed 4.

**Comment by sebastianmika** [comment]
Hi, 

yes sorry, you are absolutely right here. The second example was just wrong. I corrected it.

/S
